version: '3.8'

services:
  db:
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flights
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: